<a href="https://colab.research.google.com/github/DipeshPun/Lab_1/blob/main/ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Introduction to Numpy
Creating an array.✅
Multidimenisional array.✅
Randomly generated arrays.✅
Element wise operation.
Summerizing operations.

##Single Dimensional array

In [2]:
import numpy as np

In [ ]:
#cate an array with all the elements to be zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
#creating an array of ones
np.ones(4)

array([1., 1., 1., 1.])

In [ ]:
#create an array of sixe 10 with all elements:
np.full(5,10)

array([10, 10, 10, 10, 10])

In [ ]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [ ]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
#Create an array with evenly spaced numbers within a specified range:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

## Multi Dimensional array


In [ ]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
z=np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
z[0,1]=20
print(z)

[[ 1 20  3]
 [ 4  5  6]
 [ 7  8  9]]


In [ ]:
#z[2:3]=1
z[2]=[1, 1, 1]
z

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [ ]:
z[:,2]=[2, 2, 2]
z

array([[ 1, 20,  2],
       [ 4,  5,  2],
       [ 1,  1,  2]])

In [ ]:
np.full((3,3),10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

## Randomly generated array
Numpy can create arrays dilled with random numbers
To ensure the reproductibility, you cab set a seed using ``np.random.seed()``, It will generate the exact same random numbers for each executions.
If you remove or change the seed values, the sequence of randim numbers will be changed.

In [ ]:
np.random.rand(10)

array([0.07355823, 0.48741288, 0.67829541, 0.18055963, 0.23389325,
       0.7611296 , 0.21869261, 0.06939111, 0.97554043, 0.49441267])

In [ ]:
np.random.seed(20)
np.random.rand(5)

array([0.5881308 , 0.89771373, 0.89153073, 0.81583748, 0.03588959])

In [ ]:
np.random.randn(5, 2)

array([[-0.95044312,  1.50227571],
       [ 2.12601055,  0.24915543],
       [-0.62064216, -0.83453294],
       [ 0.91635593,  0.70783847],
       [ 0.41967613,  0.53415759]])

In [3]:
np.random.randint(low=0, high=100, size=(5, 5))

array([[74, 92, 61, 21, 96],
       [ 5, 49, 32, 94, 76],
       [72, 41, 75, 20, 25],
       [12, 71, 54, 19,  5],
       [97, 62, 44, 10, 15]])

## Element wise operation on entire arrays element by element

In [5]:
a=np.arange(5)
a

array([0, 1, 2, 3, 4])

In [6]:
b=(10+(a*2))
b

array([10, 12, 14, 16, 18])

In [19]:
#comparision operation
a*b

array([ 0, 12, 28, 48, 72])

In [16]:
a >=2

array([False, False,  True,  True,  True])

In [17]:
a > b

array([False, False, False, False, False])

In [18]:
a<b

array([ True,  True,  True,  True,  True])

In [20]:
#Summarizing of the data
#Numpy provides functions for summarizing array data
a

array([0, 1, 2, 3, 4])

In [21]:
a.std()

1.4142135623730951

In [22]:
#find min, max and sum of the array
a.min()

0

In [23]:
a.max()

4

In [24]:
a.sum()

10